# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp <- function(beta0, beta, v, values, rows, cols, y_values, y_ind, nrow, ncol) {
    .Call('fm_sp', PACKAGE = 'fm', beta0, beta, v, values, rows, cols, y_values, y_ind, nrow, ncol)
}

