# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sgd <- function(X, y, K, minibatch_size) {
    .Call('fm_sgd', PACKAGE = 'fm', X, y, K, minibatch_size)
}

rcppeigen_hello_world <- function() {
    .Call('fm_rcppeigen_hello_world', PACKAGE = 'fm')
}

rcppeigen_outerproduct <- function(x) {
    .Call('fm_rcppeigen_outerproduct', PACKAGE = 'fm', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('fm_rcppeigen_innerproduct', PACKAGE = 'fm', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('fm_rcppeigen_bothproducts', PACKAGE = 'fm', x)
}

main <- function() {
    .Call('fm_main', PACKAGE = 'fm')
}

sp3 <- function(beta0, beta, v, values, rows, cols, y, nrow, ncol) {
    .Call('fm_sp3', PACKAGE = 'fm', beta0, beta, v, values, rows, cols, y, nrow, ncol)
}

sp2 <- function(row, beta0, beta, v, values, rows, cols, nrow, ncol) {
    .Call('fm_sp2', PACKAGE = 'fm', row, beta0, beta, v, values, rows, cols, nrow, ncol)
}

sp1 <- function(values, rows, cols, nrow, ncol) {
    .Call('fm_sp1', PACKAGE = 'fm', values, rows, cols, nrow, ncol)
}

